/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/apply/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Apply Status */
        get: operations["apply_status_api_apply_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trash/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trash Status */
        get: operations["trash_status_api_trash_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trash List */
        get: operations["trash_list_api_trash_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Decisions
         * @description Compatibility endpoint for moving 'del' photos into Trash.
         *
         *     The web UI uses task type `trash_decisions`; this route stays for older
         *     clients and focused API tests.
         */
        post: operations["apply_decisions_api_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apply/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Undo Apply
         * @description Compatibility endpoint for restoring trashed photos.
         */
        post: operations["undo_apply_api_apply_undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["get_meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Images */
        get: operations["get_images_api_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Groups
         * @description Return duplicate groups (paginated by group), each with all of its
         *     member photos ordered best-first. The same filters as /api/images apply:
         *     a group is included when at least one of its members matches, but every
         *     member is returned so the full duplicate set stays reviewable.
         */
        get: operations["get_groups_api_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scenes
         * @description Return rough scene groups (paginated by scene), each with all member
         *     photos ordered best-first. Every item carries its `dup_group`, so the client
         *     nests near-duplicate sub-piles with a cheap groupBy(dup_group). Same filter
         *     semantics as /api/groups: a scene is included when at least one member
         *     matches, but every member is returned so the full scene stays reviewable.
         */
        get: operations["get_scenes_api_scenes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/regroup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regroup Scenes
         * @description Re-segment scenes by capture-time gap only (the 'scene granularity' knob).
         *     Clamped to a sane range; recomputes scene_group in place and remembers the
         *     chosen gap so the slider re-opens where the user left it.
         */
        post: operations["regroup_scenes_api_scenes_regroup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Scenes
         * @description Pin two or more scenes into one (a manual merge that survives recuts and
         *     re-analysis). Recomputes at the current gap and returns the new scene count.
         */
        post: operations["merge_scenes_api_scenes_merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/unmerge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unmerge Scene
         * @description Drop the manual-merge pins touching a scene, returning it to automatic
         *     time-gap segmentation.
         */
        post: operations["unmerge_scene_api_scenes_unmerge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/thumb/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Thumb */
        get: operations["serve_thumb_thumb__image_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/img/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Full */
        get: operations["serve_full_img__image_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Image Locations
         * @description Every path holding the exact same file bytes (matched on content_hash) as
         *     this image. Lets the UI surface 'this file also lives at N other locations'
         *     to aid organizing/consolidation. Read-only; decisions stay hash-keyed so all
         *     copies share one verdict.
         */
        get: operations["image_locations_api_images__image_id__locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal Path
         * @description Open a path in the OS file manager. Bounded to the configured photo
         *     root(s) (see --photo-root / meta.folder): the target must be a root or sit
         *     below one, so this can't be turned into an open-anything primitive — and
         *     unlike the old check, it won't open a root's ancestors (e.g. a drive).
         */
        post: operations["reveal_path_api_reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Roots */
        get: operations["get_roots_api_settings_roots_get"];
        put?: never;
        /**
         * Add Root
         * @description Add a directory to the configured photo roots. Validates it exists and is
         *     a directory, stores its resolved absolute path, and de-dupes case-insensitively.
         */
        post: operations["add_root_api_settings_roots_post"];
        /**
         * Delete Root
         * @description Remove a configured photo root by its stored path.
         */
        delete: operations["delete_root_api_settings_roots_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Folders */
        get: operations["get_folders_api_settings_folders_get"];
        put?: never;
        /**
         * Add Folder
         * @description Onboard a source folder into the catalog. It joins the analyze set and,
         *     because reveal roots are derived from the library folders, immediately
         *     becomes reveal-allowed. Re-run analysis afterwards to index its photos.
         */
        post: operations["add_folder_api_settings_folders_post"];
        /**
         * Delete Folder
         * @description Remove a folder from the catalog's source set. Already-indexed photos
         *     remain until the next re-analysis rebuilds from the remaining folders;
         *     decisions are hash-keyed and survive regardless. Also drops any matching
         *     legacy reveal root so reveal permission follows the folder out.
         */
        delete: operations["delete_folder_api_settings_folders_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fs Complete
         * @description Directory autocomplete for the settings folder field. Given a partial
         *     path, return matching child directories (full paths). If the query ends in a
         *     separator we list that directory's children; otherwise the last segment is
         *     treated as a case-insensitive prefix filter against its parent's children.
         */
        get: operations["fs_complete_api_fs_complete_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Decision */
        post: operations["set_decision_api_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rename Cluster */
        post: operations["rename_cluster_api_clusters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clusters/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Clusters
         * @description Reassign every face of the `from` cluster(s) into `into`, then drop the
         *     now-empty source cluster name rows. Pure DB edit — no re-embedding. Each
         *     moved face is also recorded as a persistent override.
         */
        post: operations["merge_clusters_api_clusters_merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/faces/{face_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Face
         * @description Move one face box to a different person. Either pass an existing
         *     `cluster_id`, or `new_person: true` (with optional `name`) to spin up a
         *     fresh identity. Recorded as a persistent override so it survives re-ingest.
         */
        post: operations["assign_face_api_faces__face_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/faces/{face_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Face
         * @description Drop a false-positive face box, decrement the image's face count, and
         *     record a persistent override so it stays deleted across re-ingest.
         */
        delete: operations["delete_face_api_faces__face_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Decisions */
        get: operations["export_decisions_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Decisions
         * @description Re-apply keep/del verdicts from an exported audit_decisions.json.
         *
         *     Each entry is matched by content hash (preferred) or, failing that, by path.
         *     Additive and non-destructive: it overwrites marks only for hashes present in
         *     the file, leaves every other existing mark untouched, and ignores the
         *     `unmarked` bucket (it carries no verdict to apply). A hash that isn't in the
         *     current catalog is still recorded — it binds if that photo is indexed later,
         *     exactly like decisions preserved across a rebuild.
         */
        post: operations["import_decisions_api_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/autocull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autocull Groups
         * @description For every duplicate group, mark the best-scoring photo 'keep' and the
         *     rest 'del'. Overwrites existing marks within groups. Marks only — files
         *     are not touched until /api/apply.
         */
        post: operations["autocull_groups_api_groups_autocull_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        /** Start Task */
        post: operations["start_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Status */
        get: operations["task_status_api_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Task Cancel */
        post: operations["task_cancel_api_tasks__task_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Task Stream
         * @description SSE replay + tail for any persisted task.
         */
        get: operations["task_stream_api_tasks__task_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Analyze */
        post: operations["start_analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analyze Status */
        get: operations["analyze_status_api_analyze_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Cancel */
        post: operations["analyze_cancel_api_analyze_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analyze Stream */
        get: operations["analyze_stream_api_analyze_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyzeStatus
         * @description Job status / start ack. Shapes vary (idle -> {state, commands};
         *     running -> full snapshot; start -> snapshot + ok), so the routes use
         *     response_model_exclude_unset=True and only the keys actually returned ship.
         */
        AnalyzeStatus: {
            /** Ok */
            ok?: boolean | null;
            /** State */
            state: string;
            /** Exit Code */
            exit_code?: number | null;
            /** Started */
            started?: number | null;
            /** Ended */
            ended?: number | null;
            /**
             * Commands
             * @default []
             */
            commands: string[];
        };
        /** ApplyResponse */
        ApplyResponse: {
            /** Moved */
            moved: number;
            /** Skipped */
            skipped: number;
            /** Rejected Dir */
            rejected_dir: string;
            /** Trash Dir */
            trash_dir?: string | null;
        };
        /** ApplyStatusResponse */
        ApplyStatusResponse: {
            /** Pending */
            pending: number;
            /** Applied */
            applied: number;
            /** Rejected Dir */
            rejected_dir: string;
            /** Trash Dir */
            trash_dir?: string | null;
            /**
             * Trashed
             * @default 0
             */
            trashed: number;
        };
        /** AssignFaceResponse */
        AssignFaceResponse: {
            /** Ok */
            ok: boolean;
            /** Cluster Id */
            cluster_id: number;
        };
        /** AutocullResponse */
        AutocullResponse: {
            /** Groups */
            groups: number;
            /** Kept */
            kept: number;
            /** Deleted */
            deleted: number;
        };
        /** ClusterFacet */
        ClusterFacet: {
            /** Cluster Id */
            cluster_id: number;
            /** Name */
            name?: string | null;
            /** Count */
            count: number;
        };
        /** Counts */
        Counts: {
            /** Total */
            total: number;
            /** With Faces */
            with_faces: number;
            /** With Portrait */
            with_portrait: number;
            /** Dup Groups */
            dup_groups: number;
            /** Scene Groups */
            scene_groups: number;
        };
        /** Face */
        Face: {
            /** Id */
            id: number;
            /** Bbox */
            bbox: number[];
            /** Prob */
            prob?: number | null;
            /** Cluster Id */
            cluster_id?: number | null;
            /** Sharp */
            sharp?: number | null;
            /** Expr */
            expr?: number | null;
        };
        /** FolderFacet */
        FolderFacet: {
            /** Path */
            path: string;
            /** Count */
            count: number;
        };
        /** FsCompleteResponse */
        FsCompleteResponse: {
            /** Entries */
            entries: string[];
            /** Truncated */
            truncated: boolean;
        };
        /** Group */
        Group: {
            /** Dup Group */
            dup_group: number;
            /** Count */
            count: number;
            /** Match Count */
            match_count: number;
            /** Items */
            items: components["schemas"]["GroupedImageItem"][];
        };
        /**
         * GroupedImageItem
         * @description An image as returned inside a group/scene: same as ImageItem plus the
         *     `matches` flag (true when the member passes the active filter).
         */
        GroupedImageItem: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Path */
            path: string;
            /** Hash */
            hash?: string | null;
            /** Combined */
            combined?: number | null;
            /** Sharpness */
            sharpness?: number | null;
            /** Para Aesthetic */
            para_aesthetic?: number | null;
            /** Para Quality */
            para_quality?: number | null;
            /** Para Composition */
            para_composition?: number | null;
            /** Para Light */
            para_light?: number | null;
            /** Para Color */
            para_color?: number | null;
            /** Para Dof */
            para_dof?: number | null;
            /** Para Content */
            para_content?: number | null;
            /** Clip Iqa */
            clip_iqa?: number | null;
            /** Dup Group */
            dup_group?: number | null;
            /** Dup Central */
            dup_central?: number | null;
            /** Scene Group */
            scene_group?: number | null;
            /** Capture Time */
            capture_time?: number | null;
            /** Caption */
            caption?: string | null;
            /** Imgw */
            imgw?: number | null;
            /** Imgh */
            imgh?: number | null;
            /** Face Sharp */
            face_sharp?: number | null;
            /** Face Expr */
            face_expr?: number | null;
            /** Portrait */
            portrait?: number | null;
            /** Decision */
            decision?: string | null;
            /** Trash State */
            trash_state?: string | null;
            /** Original Path */
            original_path?: string | null;
            /** Trashed At */
            trashed_at?: string | null;
            /**
             * Faces
             * @default []
             */
            faces: components["schemas"]["Face"][];
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Matches */
            matches: boolean;
        };
        /** GroupsResponse */
        GroupsResponse: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Groups */
            groups: components["schemas"]["Group"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageItem */
        ImageItem: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Path */
            path: string;
            /** Hash */
            hash?: string | null;
            /** Combined */
            combined?: number | null;
            /** Sharpness */
            sharpness?: number | null;
            /** Para Aesthetic */
            para_aesthetic?: number | null;
            /** Para Quality */
            para_quality?: number | null;
            /** Para Composition */
            para_composition?: number | null;
            /** Para Light */
            para_light?: number | null;
            /** Para Color */
            para_color?: number | null;
            /** Para Dof */
            para_dof?: number | null;
            /** Para Content */
            para_content?: number | null;
            /** Clip Iqa */
            clip_iqa?: number | null;
            /** Dup Group */
            dup_group?: number | null;
            /** Dup Central */
            dup_central?: number | null;
            /** Scene Group */
            scene_group?: number | null;
            /** Capture Time */
            capture_time?: number | null;
            /** Caption */
            caption?: string | null;
            /** Imgw */
            imgw?: number | null;
            /** Imgh */
            imgh?: number | null;
            /** Face Sharp */
            face_sharp?: number | null;
            /** Face Expr */
            face_expr?: number | null;
            /** Portrait */
            portrait?: number | null;
            /** Decision */
            decision?: string | null;
            /** Trash State */
            trash_state?: string | null;
            /** Original Path */
            original_path?: string | null;
            /** Trashed At */
            trashed_at?: string | null;
            /**
             * Faces
             * @default []
             */
            faces: components["schemas"]["Face"][];
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /** ImagesResponse */
        ImagesResponse: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Items */
            items: components["schemas"]["ImageItem"][];
        };
        /** Location */
        Location: {
            /** Id */
            id: number;
            /** Path */
            path: string;
            /** Exists */
            exists: boolean;
        };
        /** LocationsResponse */
        LocationsResponse: {
            /** Hash */
            hash?: string | null;
            /** Count */
            count: number;
            /** Locations */
            locations: components["schemas"]["Location"][];
        };
        /** MergeResponse */
        MergeResponse: {
            /** Ok */
            ok: boolean;
            /** Moved */
            moved: number;
        };
        /** MergeScenesRequest */
        MergeScenesRequest: {
            /** Scene Groups */
            scene_groups: number[];
        };
        /** MetaResponse */
        MetaResponse: {
            /** Meta */
            meta: {
                [key: string]: string;
            };
            /** Clusters */
            clusters: components["schemas"]["ClusterFacet"][];
            /** Tags */
            tags: components["schemas"]["TagFacet"][];
            /** Folders */
            folders: components["schemas"]["FolderFacet"][];
            ranges: components["schemas"]["Ranges"];
            counts: components["schemas"]["Counts"];
            /** Histograms */
            histograms: {
                [key: string]: number[];
            };
            /** Has Para */
            has_para: boolean;
            /** Has Portrait */
            has_portrait: boolean;
            /** Photo Roots */
            photo_roots: string[];
        };
        /** OkResponse */
        OkResponse: {
            /** Ok */
            ok: boolean;
        };
        /** Ranges */
        Ranges: {
            /** Cmin */
            cmin?: number | null;
            /** Cmax */
            cmax?: number | null;
            /** Smin */
            smin?: number | null;
            /** Smax */
            smax?: number | null;
            /** Amin */
            amin?: number | null;
            /** Amax */
            amax?: number | null;
        };
        /** RegroupRequest */
        RegroupRequest: {
            /** Gap */
            gap: number;
        };
        /** RegroupResponse */
        RegroupResponse: {
            /** Scene Groups */
            scene_groups: number;
            /** Gap */
            gap: number;
        };
        /** RootsResponse */
        RootsResponse: {
            /** Photo Roots */
            photo_roots: string[];
        };
        /** Scene */
        Scene: {
            /** Scene Group */
            scene_group: number;
            /** Count */
            count: number;
            /** Match Count */
            match_count: number;
            /** Dup Sets */
            dup_sets: number;
            /**
             * Manual
             * @default false
             */
            manual: boolean;
            /** Time Start */
            time_start?: number | null;
            /** Time End */
            time_end?: number | null;
            /** Items */
            items: components["schemas"]["GroupedImageItem"][];
        };
        /** ScenesResponse */
        ScenesResponse: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Scenes */
            scenes: components["schemas"]["Scene"][];
        };
        /** TagFacet */
        TagFacet: {
            /** Tag */
            tag: string;
            /** Count */
            count: number;
        };
        /** TaskListResponse */
        TaskListResponse: {
            /** Tasks */
            tasks: components["schemas"]["TaskSnapshot"][];
            current?: components["schemas"]["TaskSnapshot"] | null;
        };
        /** TaskSnapshot */
        TaskSnapshot: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** State */
            state: string;
            /** Phase */
            phase?: string | null;
            /** Progress */
            progress?: number | null;
            /** Message */
            message?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /** Started */
            started?: number | null;
            /** Ended */
            ended?: number | null;
            /** Commands */
            commands?: string[];
        };
        /** TaskStartRequest */
        TaskStartRequest: {
            /** Type */
            type: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** TrashItem */
        TrashItem: {
            /** Id */
            id: number;
            /** Image Id */
            image_id?: number | null;
            /** Filename */
            filename: string;
            /** Hash */
            hash?: string | null;
            /** Original Path */
            original_path: string;
            /** Trash Path */
            trash_path: string;
            /** State */
            state: string;
            /** Trashed At */
            trashed_at?: string | null;
        };
        /** TrashListResponse */
        TrashListResponse: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["TrashItem"][];
        };
        /** TrashStatusResponse */
        TrashStatusResponse: {
            /** Pending */
            pending: number;
            /** Trashed */
            trashed: number;
            /** Emptied */
            emptied: number;
            /** Trash Dir */
            trash_dir: string;
        };
        /** UndoResponse */
        UndoResponse: {
            /** Restored */
            restored: number;
            /** Skipped */
            skipped: number;
        };
        /** UnmergeSceneRequest */
        UnmergeSceneRequest: {
            /** Scene Group */
            scene_group: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apply_status_api_apply_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyStatusResponse"];
                };
            };
        };
    };
    trash_status_api_trash_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashStatusResponse"];
                };
            };
        };
    };
    trash_list_api_trash_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashListResponse"];
                };
            };
        };
    };
    apply_decisions_api_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResponse"];
                };
            };
        };
    };
    undo_apply_api_apply_undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UndoResponse"];
                };
            };
        };
    };
    get_meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    get_images_api_images_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                sort?: string;
                dir?: string;
                score_min?: number;
                score_max?: number;
                sharp_min?: number;
                sharp_max?: number;
                aes_min?: number;
                aes_max?: number;
                portrait_min?: number;
                portrait_max?: number;
                tags?: string | null;
                people?: string | null;
                folder?: string | null;
                folder_recursive?: boolean;
                dup_mode?: string;
                decision?: string;
                trash?: string;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_groups_api_groups_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                order?: string;
                score_min?: number;
                score_max?: number;
                sharp_min?: number;
                sharp_max?: number;
                aes_min?: number;
                aes_max?: number;
                portrait_min?: number;
                portrait_max?: number;
                tags?: string | null;
                people?: string | null;
                folder?: string | null;
                folder_recursive?: boolean;
                decision?: string;
                trash?: string;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenes_api_scenes_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                order?: string;
                score_min?: number;
                score_max?: number;
                sharp_min?: number;
                sharp_max?: number;
                aes_min?: number;
                aes_max?: number;
                portrait_min?: number;
                portrait_max?: number;
                tags?: string | null;
                people?: string | null;
                folder?: string | null;
                folder_recursive?: boolean;
                decision?: string;
                trash?: string;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regroup_scenes_api_scenes_regroup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegroupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_scenes_api_scenes_merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeScenesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unmerge_scene_api_scenes_unmerge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnmergeSceneRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_thumb_thumb__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_full_img__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    image_locations_api_images__image_id__locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_path_api_reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roots_api_settings_roots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootsResponse"];
                };
            };
        };
    };
    add_root_api_settings_roots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_root_api_settings_roots_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_folders_api_settings_folders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    add_folder_api_settings_folders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_folder_api_settings_folders_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fs_complete_api_fs_complete_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FsCompleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_decision_api_decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_cluster_api_clusters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_clusters_api_clusters_merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_face_api_faces__face_id__assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                face_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignFaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_face_api_faces__face_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                face_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_decisions_api_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    import_decisions_api_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autocull_groups_api_groups_autocull_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutocullResponse"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_status_api_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_cancel_api_tasks__task_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_stream_api_tasks__task_id__stream_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_status_api_analyze_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeStatus"];
                };
            };
        };
    };
    analyze_cancel_api_analyze_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    analyze_stream_api_analyze_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
